### ISSUE TITLE
Correct sort after adding a new element

### ISSUE THREAD

**Issue by igor-lemon** [prescottprue/redux-firestore#106] opened 2018-05-21 23:56 UTC
After adding a new item the `ordered` collection has wrong sorting. New element has last position but after page refresh it element has first position (I didn't apply any sort filters).

**Comment by prescottprue** [comment] 2018-05-22 09:55
Please provide listener settings. It is difficult to fully reproduce issues without listeners and connect logic.

Document updates from Firestore include old and new index, which are used by the reducer to place within state. Without knowing the listener (i.e. what level the update is occurring within state) hard to tell why this wouldn't be happening.

**Comment by prescottprue** [comment] 2018-05-25 22:30
@igor-lemon Is it possible to provide listener and connect settings to repro?

**Comment by prescottprue** [comment] 2018-10-02 00:28
Closing since replication was not provided.

**Closed by prescottprue** 2018-10-02 00:28 UTC
Labels: needs-replication
