### ISSUE TITLE
Items deleted from array field not reflected in Redux firestore.ordered state

### ISSUE THREAD

**Issue by jpierce42** [prescottprue/redux-firestore#162] opened 2019-01-02 19:20 UTC
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
When updating an array field on a document, if items are deleted from the array, the field is not updated correctly in the 'ordered' Redux state.  

[See very basic example here](https://repl.it/repls/JampackedEagerPhysics).   I want to delete value `a` from the item's current list of values `[a, b]`.  After a successful `DOCUMENT_MODIFIED` action, the data is correct in the `data` state (`[b]`), but in `ordered`, the values are `[b, b]`.

Looks like this is a result of calling `merge` from `modifyDoc` in the `orderedReducer`.  It looks like I would get my desired behavior from `assign`, but not sure how this affects other use cases.

**What is the expected behavior?**
If an item is deleted from an array field, the correct shortened array should appear in the `ordered` Redux state.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
Currently using:
"react-redux-firebase": "^2.2.6",
"redux-firestore": "^0.5.8"

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
I'm happy to set up a fully working demo if you'd like to see the full process.  The Firestore update works fine:

1. Create a document in Firestore with an array field, adding multiple values to the array.
2. Use redux-firestore to issue an update call deleting an item from the array.  
```
      const itemUpdates =  {
        values: [1] // Goal is to overwrite existing array with a shorter array
      }
      return this.props.firestore.update(
        { collection: 'items', doc: query.itemID },
        itemUpdates
      )
```
3.  After successful `DOCUMENT_MODIFIED`, inspect Redux Firestore state: `item.values` in firestore.data  will be the correct, shortened array `[1]`, while in firestore.ordered it will have the incorrectly merged array `[1, 1]`.

Let me know if you have any questions or if I've missed something obvious.  Thanks again for the great library, really enjoying working with it.

**Comment by prescottprue** [comment] 2019-01-02 19:49
Thanks for the detailed repro steps. I believe this is a duplicate of [#140](https://github.com/prescottprue/redux-firestore/issues/140), if so, it is due to supporting subcollections, so fixing this can cause a regressing in `0.5.*` or `0.6.*`. The `1.*.*` versions available on the `next` branch should be easier to address this issue, if it isn't already

**Comment by jpierce42** [comment] 2019-01-02 20:17
Oh, yes, looks like a duplicate.  I'll keep an eye on the roadmap.  Thanks for the quick reply!

**Closed** 2019-01-02 20:36 UTC
