### ISSUE TITLE
feat(query): support FieldsPath.documentId in where

### ISSUE THREAD

**Issue by jancama2** [prescottprue/redux-firestore#176] opened 2019-02-05 11:43 UTC
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
Firestore gives you chance to use :
```
db
   .collection('books')
   .where(FieldPath.documentId(), '==', 'fK3ddutEpD2qQqRMXNW5')
   .get()
```
But I cant use FieldPath.documentId in:
```
firestore.setListener({
  collection: ...,
  where: [  FieldPath.documentId(), '==', 'fK3ddutEpD2qQqRMXNW5' ], 
```

I have to hack it with:
```
firestore.setListener({
  collection: ...,
  where: ['__name__',  '==', 'fK3ddutEpD2qQqRMXNW5' ], 
```
**What is the expected behavior?**
To be able to write:
```
firestore.setListener({
  collection: ...,
  where: [  FieldPath.documentId(), '==', 'fK3ddutEpD2qQqRMXNW5' ], 
```

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
redux-firestore@0.6.0
**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**Comment by prescottprue** [comment] 2019-02-07 04:47
@jancama2 Maybe I am missing something, but Is it not possible to just do:

```js
firestore.setListener({
  collection: 'books'
  doc: 'fK3ddutEpD2qQqRMXNW5'
})
```

Since you are talking about the document id? Equivelant to `collection('books').doc('fK3ddutEpD2qQqRMXNW5')`?

**Comment by jancama2** [comment] 2019-02-07 08:56
It is but when you need to do nested where with id reference then it is a problem:
```
[
  [  FieldPath.documentId(), '==', 'fK3ddutEpD2qQqRMXNW5' ],
  [  'isPublic', '==', true ],
]
```

**Comment by jancama2** [comment] 2019-02-07 08:59
I know it is an edge case, I do this `where` with id for security reasons. But the main idea about this bug is that firestore api gives you the ability to use `FieldPath.documentId()` and `redux-firestore` is not supporting it so it might be a good idea to support it :).

**Comment by leoxs22** [comment] 2020-01-02 15:47
This feature would be great for getting several documents.

For example: 

`where: [FieldPath.documentId(), "in", [2,5,9]]`

**Comment by prescottprue** [comment] 2020-01-06 05:50
When trying this currently in v3.0.6, it works as expected both with a single ID and the `in` case when using from `useFirestore` hook:

```js
import React, { useEffect } from 'react';
import { useSelector } from 'react-redux';
import { useFirestore } from 'react-redux-firebase';

function Todos() {
  const todoIds = useSelector(state => state.firestore.ordered.todos)
  const firestore = useFirestore()

  const listenerSettings = {
    collection: 'todos',
    where: [firestore.FieldPath.documentId(), "==", "L6eIsQKlTFIQlg5Tl5AD"]],
    // or multiple:
    // where: [
    //  firestore.FieldPath.documentId(),
    //  "in",
    //  ["L6eIsQKlTFIQlg5Tl5AD", "A5eIsQKlTFIQlg5Tl8SH"]
    // ]
  }

  useEffect(() => {
    firestore.setListener(listenerSettings)
    return function cleanup() {
      firestore.unsetListener(listenerSettings)
    }
  }, [])

  return (
    // Rest of component
 )
}
```


or when importing directly from Firebase:

```js
import React, { useEffect } from 'react';
import { useSelector } from 'react-redux';
import { useFirestore } from 'react-redux-firebase';
import firebase from 'firebase/app';
import 'firebase/firestore';

const listenerSettings = {
  collection: 'todos',
  where: [firebase.firestore.FieldPath.documentId(), "==", "L6eIsQKlTFIQlg5Tl5AD"]],
  // or multiple:
  // where: [
  //  firebase.firestore.FieldPath.documentId(),
  //  "in",
  //  ["L6eIsQKlTFIQlg5Tl5AD", "A5eIsQKlTFIQlg5Tl8SH"]
  // ]
}

function Todos() {
  const todoIds = useSelector(state => state.firestore.ordered.todos)
  const firestore = useFirestore()

  useEffect(() => {
    firestore.setListener(listenerSettings)
    return function cleanup() {
      firestore.unsetListener(listenerSettings)
    }
  }, [])

  return (
    // Rest of component
 )
}
```

Is this not working for you @jancama2 or @leoxs22? Going to close this for now since it seems to be working - will reopen if we have a repro

**Closed by prescottprue** 2020-01-06 05:50 UTC
Labels: enhancement

**Comment by leoxs22** [comment] 2020-01-06 18:13
It's working, I had the last redux-firestore version, but I was outdated with react-redux-firebase, which was causing the error.

Thanks!

**Comment by acsands13** [comment] 2020-04-24 15:50
Is it possible to use a `.documentId()` query directly with `useFirestoreConnect()` instead of having to set listeners manually with `useFirestore()`? E.g. something like:

```js
import React from 'react';
import { useSelector } from 'react-redux';
import { useFirestoreConnect } from 'react-redux-firebase';

const Index = props => {
  const userBooks = useSelector(state => state.firebase.profile.books);  // already waited for this data to load in a parent component
  useFirestoreConnect([{
    collection: 'books',
    where: ['[reference documentId() somehow]', 'in', userBooks],
  }]);

  ...
}
```

**Comment by prescottprue** [comment] 2020-04-27 01:23
@acsands13 You should be able to do that if you pull in `FieldPath` from Firebase's SDK directly and use `FieldPath.documentId()`. If you have issues doing so, please open a new issue with the code to reproduce the issue

**Comment by sreeharicubet** [comment] 2020-05-01 07:39
@acsands13  please try this
```
import { useFirestore, useFirestoreConnect } from 'react-redux-firebase'

const firestore = useFirestore()
useFirestoreConnect([{
    collection: 'books',
    where: [firestore.FieldPath.documentId(), 'in', userBooks],
  }]);
```

**Comment by acsands13** [comment] 2020-05-01 13:41
Thanks for the replies! @sreeharicubet I was using that to begin with, and it worked, but realized a bit later that `in` queries are limited to 10. So ended up going with this, which seems to accomplish what I was hoping for (and no 10 limit):

```js
import { useFirestoreConnect } from 'react-redux-firebase';

useFirestoreConnect((userBooks).map(bookId => ({
  collection: 'books',
  doc: bookId,
})));
```

**Comment by dsgriffin** [comment] 2021-07-08 14:42
> @acsands13 please try this
> 
> ```
> import { useFirestore, useFirestoreConnect } from 'react-redux-firebase'
> 
> const firestore = useFirestore()
> useFirestoreConnect([{
>     collection: 'books',
>     where: [firestore.FieldPath.documentId(), 'in', userBooks],
>   }]);
> ```

When I try this, I get the error `Property 'documentId' does not exist on type 'FieldPath'`

The `FieldPath` property retrieved via. `useFirestore` only has an `isEqual` property, no others.
