### ISSUE TITLE
(question) Recursive subscription

### ISSUE THREAD

**Issue by skucher** [prescottprue/redux-firestore#94] opened 2018-05-10 04:24 UTC
### My firestore document layout
```
rootcollection
    doc1
       subcollection11
          subdoc1
          subdoc2
    doc2
       subcollection21
```
### For example
- root level doc addition/removal/change
- subcollection addition/removal/change
- subdoc1 addition/removal/change

### I tried
```
import { getFirestore } from 'redux-firestore';
getFirestore().get('/rootcollection') or getFirestore().setListeners('/rootcollection')
```
But it did not give me any data on subcollection level.
Do i need to handle the subscription myself on client level? Or is there a better way?

**Comment by prescottprue** [comment] 2018-05-10 18:08
@skucher That is expected, and this may be a dupe of #52. When creating a listener you point to a collection or a document, but neither automatically include subcollections. Automatically doing so was intentionally avoided since it could have major performance and cost implications in some cases.

In order to get a document and a subcollection of that document you have to provided listener settings for that:

```js
setListeners([
  {
    collection: 'cities',
    doc: 'SF'
  },
  {
    collection: 'cities',
    doc: 'SF',
    subcollections: [{ collection: 'zipcodes' }]
  },
])
```

There has been discussion of an option to allow for both within a single query configuration, but that feature has not yet been added.

Going to close as a duplicate, but let me know if I am misunderstanding.

**Comment by skucher** [comment] 2018-05-11 07:59
Thank you very much. 
Let me explain my simplified use case.

Having the tree structure as in above example and knowing only the *rootcollection* name i would like to show the tree above to my user. And refresh it on every update, done by my app or any other app that updates any level of data under *rootcollection*.

Is it possible / recommended to use redux-firestore for that?

**Note:**
I have idea how to do it manually, but the major challange is to be able to subscribe to the subollection of the doc that created outside of my app.

**Comment by prescottprue** [comment] 2018-05-11 19:12
There is not currently a way to check for subcollections that you don't know the name of using Firestore's client API, they suggest doing it within a cloud function with the Firebase Admin SDK [as mentioned in this stackoverflow post](https://stackoverflow.com/questions/48258632/fetching-all-collections-in-firestore) and a few places in the Firebase docs.

My suggestion is to have a function handle getting the subcollection name using the admin SDK, then you can call that function from the client. Once the client has the subcollection name it can query for the data it needs. Be careful with security when using this pattern though.

**Comment by CoVoCre** [comment] 2018-07-24 09:44
@skucher here is the [doc from firestore](https://firebase.google.com/docs/firestore/query-data/get-data#list_subcollections_of_a_document), they suggest if you need this ( actually they show one such use case in their [distributed counters/sharding example](https://firebase.google.com/docs/firestore/solutions/counters) ) :

>  If you find that you need this capability in the mobile/web client libraries, consider restructuring your data so that subcollection names are predictable.

**Closed as completed** 2018-07-29 09:24 UTC
