### ISSUE TITLE
Querying nonexistent data adds an entry in firestore.ordered but not firestore.data

### ISSUE THREAD

**Issue by diagramatics** [prescottprue/redux-firestore#44] opened 2017-12-20 08:59 UTC
**Do you want to request a *feature* or report a *bug*?**  

- [x] Bug

Not sure if this is intentional or not though, but inconsistent to rely on I find. Happy to make a PR to correct them — just needs to double check to see if this is a bug or not.

**What is the current behavior?**

Consider this action:
```js
{
  type: '@@reduxFirestore/LISTENER_RESPONSE',
  meta: {
    collection: 'group',
    doc: 'uJH3akkXRkje3ruPZ7au',
    subcollections: [
      {
        collection: 'userAccess',
        doc: 'nonexistent'
      }
    ],
    storeAs: 'group/uJH3akkXRkje3ruPZ7au/userAccess/'
  },
  payload: {
    data: null,
    ordered: []
  }
}
```

Will result in the store being updated as:

```js
{ 
  firestore: {
    ordered: {
      group/uJH3akkXRkje3ruPZ7au/userAccess/: []
    }
  }
}
```

Which is supposedly inconsistent with how the store's `firestore.data` gets updated, and the action payload being incorrect based on the docs of the `orderedFromSnap()` return type, which is `Array|null`.

**What is the expected behavior?**

The `action.payload` should be:

```js
payload: {
  data: null,
  ordered: null
}
```

And the store's `firestore.data` should have an entry of `group/uJH3akkXRkje3ruPZ7au/userAccess/` as `null` instead of `undefined` and that part of the store not being updated. This way the `isLoaded` check from `react-redux-firebase` can rely on the behavior of `firestore.data` on that part.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**

Running `redux-firestore` `0.2.5`.

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

Query an endpoint that will return `null` as the payload data. In my case it was a nonexistent document in a collection.

**Comment by prescottprue** [comment] 2018-02-07 07:42
Closing since this is seems to be a duplicate of #44

**Closed by prescottprue** 2018-02-07 07:42 UTC
