### ISSUE TITLE
Data on page view not auto reloading on firestore change?

### ISSUE THREAD

**Issue by Frank-The-Tank** [prescottprue/redux-firestore#154] opened 2018-11-21 02:00 UTC
Hey guys, I am currently having a problem when updating data on a page. I want to be able to update some data which then calls a function in my action controller that updates data in firestore. I am able to update the data and call the method and the firestore data is updated, but my client does not show the change? How do I make it so whenever something changes in my firestore database the view for my client is refreshed if they are the page containing that data?

I am currently using  firestoreConnect to try and tie the data to my view but the only way I can see updates I have made is to refresh the page manually. 

My code is as follows: 

**BudgetDashboard.jsx**
```import React, { Component } from "react";
import { connect } from "react-redux";
import { firestoreConnect, isLoaded } from "react-redux-firebase";
import { compose } from "redux";
import { Grid } from "semantic-ui-react";
import BudgetHeader from "../BudgetHeader/BudgetHeader";
import BudgetList from "../BudgetList/BudgetList";
import BudgetNav from "../BudgetNav/BudgetNav";
import { updateData, updateBudgetData, loadBudget, compareChooser } from "../budgetActions";
import LoadingComponent from "../../../app/layout/LoadingComponent";

const mapState = state => ({
  users: state.firestore.ordered.users
});

const actions = {
  updateData,
  updateBudgetData,
  loadBudget,
  compareChooser
};

class BudgetDashboard extends Component {
  updateBudgetData = (newData, fieldToUpdate) => {
    this.props.updateBudgetData(newData, fieldToUpdate);
  };

  onCompareChange = (event, data) => {
    if (data.checked) {
      this.props.compareChooser("net");
    } else {
      this.props.compareChooser("gross");
    }
  };

  render() {
    const { users } = this.props;
    if (!isLoaded(users)) return <LoadingComponent inverted={true} />;
    return (
      <Grid>
        <Grid.Column width={16}>
          <BudgetNav />
          <BudgetHeader
            general={users[0].budget[1]}
            onCompareChange={this.onCompareChange}
          />
          <BudgetList
            className="standardSeparation"
            data={users[0].budget[0]}
            unallocatedBudget={users[0].budget[1].unallocatedBudget}
            unallocatedSpending={users[0].budget[1].unallocatedSpending}
            updateData={this.updateBudgetData}
          />
        </Grid.Column>
      </Grid>
    );
  }
}

export default compose(
  connect(
    mapState,
    actions
  ),
  firestoreConnect([
    {
      collection: "users",
      doc: "dafasdfsadfasfasdf",
      subcollections: [{ collection: "budget" }]
    }
  ])
)(BudgetDashboard);```

**budgetActions**
`export const updateBudgetData = (inputData, fieldToUpdate) => {
  return async (dispatch, getState, { getFirebase, getFirestore }) => {
    try {
      const firestore = getFirestore();

      // Get all firestore data nodes that will be used for updating after data change
      const userBudget = firestore
        .collection("users")
        .doc("asdfasdfsadfasfsadfsafd")
        .collection("budget");
      const userGeneralRef = userBudget.doc("general");
      const userDataRef = userBudget.doc("data");

      await userDataRef
        .get()
        .then(function(doc) {
          if (doc.exists) {
            const updatedMap = generateUpdatedMap(doc.data(), inputData, fieldToUpdate);
            userDataRef.set(updatedMap);
          } else {
            console.log("No document data");
          }
        })
        .catch(function(error) {
          console.log("Error: ", error);
        });

      toastr.success("Success!", "Budget data has been updated");
    } catch (error) {
      toastr.error("Oops", "Something went wrong");
    }
  };
};`




**BudgetListComponent**
```
import React, { Component } from "react";
import { Accordion, Icon, List, Menu, Grid } from "semantic-ui-react";
import ClickToEdit from "../../../app/common/util/ClickToEdit/ClickToEdit";

class BudgetListContent extends Component {
  render() {
    const { data, updateData, unallocatedBudget, unallocatedSpending } = this.props;

    const panels =
      data &&
      data.content.map(rec => ({
        key: rec.id,
        title: (
          <Accordion.Title
            className="secondaryBkgTheme rounded"
            style={{ marginBottom: 5 }}
          >
            <Icon name="dropdown" />
            <Icon name={rec.icon} style={{ marginRight: 10 }} />
            <span>{rec.title}</span>
            <span style={{ position: "absolute", left: 218 }}>
              <span>${parseFloat(rec.budgeted).toFixed(2)}</span>
            </span>
            <span style={{ position: "absolute", left: 368 }}>
              ${parseFloat(rec.spent).toFixed(2)}
            </span>
            <span style={{ position: "absolute", left: 518 }}>
              ${parseFloat(rec.leftover).toFixed(2)}
            </span>
            <span style={{ position: "absolute", left: 668 }}>
              <span className="greenBudgetBox" />
              <span>{rec.atlasScore}</span>
            </span>
            <span style={{ float: "right", paddingRight: 10 }}>
              {parseFloat(rec.budgetedPercent).toFixed(1)}%
            </span>
          </Accordion.Title>
        ),
        content:
          rec.sections &&
          rec.sections.map(subRec => (
            <List key={subRec.id} divided relaxed style={{ marginLeft: 10 }}>
              <List.Item>
                <List.Icon name={subRec.icon} />
                <List.Content>
                  <span style={{ marginTop: 1 }}>{subRec.title}</span>
                  <span
                    style={{
                      position: "absolute",
                      left: 218,
                      display: "inline-flex"
                    }}
                  >
                    <span>$</span>
                    <ClickToEdit
                      wrapperClass="editableBudgetLabel"
                      inputClass="editableBudgetInput"
                      textClass="editableBudgetText"
                      fieldAffected={{
                        sectionId: data.id,
                        headerId: rec.id,
                        itemId: subRec.id,
                        column: "budgeted"
                      }}
                      value={parseFloat(subRec.budgeted)
                        .toFixed(2)
                        .toString()}
                      endEditing={updateData}
                    />
                  </span>
                  <span
                    style={{
                      position: "absolute",
                      left: 368,
                      display: "inline-flex"
                    }}
                  >
                    <span>$</span>
                    <ClickToEdit
                      wrapperClass="editableBudgetLabel"
                      inputClass="editableBudgetInput"
                      textClass="editableBudgetText"
                      fieldAffected={{
                        sectionId: data.id,
                        headerId: rec.id,
                        itemId: subRec.id,
                        column: "spent"
                      }}
                      value={parseFloat(subRec.spent)
                        .toFixed(2)
                        .toString()}
                      endEditing={updateData}
                    />
                  </span>
                  <span style={{ position: "absolute", left: 518 }}>
                    ${parseFloat(subRec.leftover).toFixed(2)}
                  </span>
                  <span style={{ position: "absolute", left: 668 }}>
                    <span className="redBudgetBox" />
                    <span>{subRec.atlasScore}</span>
                  </span>
                  <span style={{ float: "right", paddingRight: 10 }}>
                    <Icon name="minus circle" />
                  </span>
                  <span
                    style={{
                      float: "right",
                      paddingRight: 10,
                      display: "inline-flex"
                    }}
                  >
                    <span>{parseFloat(subRec.budgetedPercent).toFixed(1)}</span>
                    <span>%</span>
                  </span>
                </List.Content>
              </List.Item>
            </List>
          ))
      }));

    return (
      <div>
        <Grid
          columns={2}
          divided
          textAlign="center"
          verticalAlign="middle"
          style={{ marginBottom: 5 }}
        >
          <Grid.Column>
            <span style={{ marginRight: 10 }}>Leftover Budget Funds:</span>
            <span style={{ color: "green" }}>
              ${data && parseFloat(unallocatedBudget).toFixed(2)}
            </span>
          </Grid.Column>
          <Grid.Column>
            <span style={{ marginRight: 10 }}>Leftover Monthly Spending:</span>
            <span style={{ color: "green" }}>
              ${data && parseFloat(unallocatedSpending).toFixed(2)}
            </span>
          </Grid.Column>
        </Grid>
        <Menu secondary style={{ marginBottom: 0, marginTop: 0 }}>
          <Menu.Item
            name="Category"
            className="budgetListHeader"
            style={{ left: 0 }}
          />
          <Menu.Item
            name="Budgeted"
            className="budgetListHeader"
            style={{ left: 200 }}
          />
          <Menu.Item
            name="Spent"
            className="budgetListHeader"
            style={{ left: 350 }}
          />
          <Menu.Item
            name="Leftover"
            className="budgetListHeader"
            style={{ left: 500 }}
          />
          <Menu.Item
            name="AtlasScore"
            className="budgetListHeader"
            style={{ left: 650 }}
          />
        </Menu>
        <Accordion
          defaultActiveIndex={[0, 1, 2, 3]}
          panels={panels}
          exclusive={false}
          fluid
        />
      </div>
    );
  }
}

export default BudgetListContent;
```

**Comment by prescottprue** [comment] 2018-11-24 02:43
@Frank-The-Tank Try placing `firestoreConnect` above `connect` to see if things correctly update. 

If that doesn't help - try using [`storeAs`](https://github.com/prescottprue/redux-firestore#storeas) to bring the sub-collection data to the top level.

The current plan, [as outlined in the v1.0.0 Roadmap](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap) is to have all subcollections stored at the top level (like normal collections) to address issues with deep updates within state.

**Comment by Frank-The-Tank** [comment] 2018-11-24 06:41
@prescottprue I think it has to have something to do with how I am displaying my data in some way since some of the data I send in all of my components is actually working.

**Comment by Frank-The-Tank** [comment] 2018-11-24 06:49
@prescottprue I have a feeling it could be because of how I am displaying the data, I am using a Semantic UI React Accordian with a custom made panel and anything in that panel is not auto updating, but data above my Accordian object in the div is reloading dynamically. I will post my "BudgetListContent" file above that shows how I am displaying all of my data. The prop "data" is what is passed with all of the firestore data I need.

**Comment by Frank-The-Tank** [comment] 2018-11-24 22:10
Ya that seems to be my problem, for instance the page is auto updating the prop that I passed like this: "unallocatedBudget={users[0].budget[1].unallocatedBudget}" but not the prop that I sent as a full map structure instead of just one point in firestore. The one where none of the data auto updates is: "data={users[0].budget[0]}"

**Comment by Frank-The-Tank** [comment] 2018-11-24 23:10
@prescottprue Ok upon even further inspection I noticed in my redux DevTools that when I am updating/setting the "userDataRef" at the end of my updateBudgetData function in budgetActions.jsx that it is creating a new document instead of replacing the old one so that might be the problem, that new document is not reflected in firebase though it shows it as updating the old document

**Comment by prescottprue** [comment] 2018-11-27 16:36
Can I get a re-explanation of where the issue stands? Should we close or are you saying that there is still an issue on your end?

**Comment by YuvalKlein** [comment] 2019-01-21 13:07
waiting too for the solution
thank you!

**Comment by Manouli** [comment] 2019-02-08 01:45
@prescottprue I think I m having the a similar issue. I m using the update method and I m updating my document. I can see the document getting updated in the in state and database.  `firestore.ordered` gets updated but order remains the same. Is there a way to get the new ordered data until this gets properly investigated? For example if I have a list of items and I order them by dateUpdated if then the dateUpdated gets updated how do I update my ordered view? Thank you very much in advance.

**Comment by YuvalKlein** [comment] 2019-02-11 11:39
Hey prescottprue
there are news with this issue?
Thank you

**Comment by prescottprue** [comment] 2019-02-11 23:23
@YuvalKlein Have you tried any of the solutions posted above? I believe there are a number of potential issues and other things being discussed here so it is hard to tell what is being referenced

Things to check out that may be related:

* [v0.7.0](https://github.com/prescottprue/redux-firestore/pull/177) (not yet released) which has a fix for updating values in documents. This was due to another feature, so it has been taking a little bit to come up with a way to make it so things aren't as breaking for some setups.
* [The v1.0.0 Roadmap](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap) which discusses how the newer versions (available on `alpha`) plan to address issues like this by design.

If you are trying these things out and they are not working please reach out with code with which the issue can be reproduced. Something like a whole repo/folder or a codesandbox helps so the issue can be replicated right away.

@Frank-The-Tank Did you solve the original issue you were seeing or not? It seems like you may have thought it was just the UI updating, but then maybe not?

**Comment by YuvalKlein** [comment] 2019-02-14 08:26
Thank you!
here I make a new array after delete the user
```
removeFromSessionHandler = () => {
		const players = this.props.session.players.filter((player) => player.uid !== this.props.auth.uid);
		this.props.removeFromSession(this.props.session, players);
```
and here in main action I update FB:
```
export const removeFromSession = (session, players) => {
	return async (dispatch, getState, { getFirestore }) => {
		// make async call to database
		try {
			const firestore = getFirestore();
			await firestore.collection('sessionList').doc(session.id).update({ players: players });
			console.log('Player successfully removed from class!');
			dispatch({ type: 'REMOVE_PLAYER_FROM_SESSION', session: session });
		} catch (err) {
			console.error('Error removing from class: ', err);
		}
	};
};
```
here is the github repo: https://github.com/YuvalKlein/play-react.git

**Comment by prescottprue** [comment] 2019-02-14 10:57
@YuvalKlein It looks like what you are experiencing is a duplicate of #140 and should be fixed as part of the [`v0.7.0` release](https://github.com/prescottprue/redux-firestore/pull/177) as mentioned above.

**Comment by prescottprue** [comment] 2019-03-10 20:06
@YuvalKlein Have you tried with `v0.7.1`?

**Comment by YuvalKlein** [comment] 2019-03-12 11:08
it's work in 0.7.0
actually I responded in the other thread, thought u got it, sorry..
Thank you!

**Closed** 2019-03-12 22:52 UTC
