### ISSUE TITLE
feat(query): support for populate on queries

### ISSUE THREAD

**Issue by muhammadsayuti** [prescottprue/redux-firestore#48] opened 2018-01-06 09:38 UTC
Do you have any thought about making populate feature for this like in react-redux-firebase ?

While subcollection is good but based on the documentation said:
Limitations: You can't easily delete subcollections, or perform compound queries across subcollections.

Well if you want me to help i have some sample to make this work that i take from your pupulate.js file in react-redux-firebase with some additional features like:
- nested object populate
- populate as different child name using as property in populate object
- populate object inside array

Just let me know if you're interested.

**Comment by prescottprue** [comment] 2018-01-06 19:55
@muhammadsayuti Definitely interested, and there have been a few people already looking for this feature. [Here is the issue on react-redux-firebase](https://github.com/prescottprue/react-redux-firebase/issues/362) where the feature was requested.

This will most likely require changes in both `redux-firestore` and `react-redux-firebase`.

Feel free to post what you have or reach out over [gitter](https://gitter.im/redux-firestore/Lobby).

**Comment by marcorm** [comment] 2018-06-30 13:08
This would be really useful!!

**Comment by Ajlanclos** [comment] 2018-08-31 03:55
What is the status on this? Also, is it possible to get root collection that are references? If it is, can someone link me an example?

Thanks!

**Comment by prescottprue** [comment] 2018-11-02 09:28
Got a basic version of this working by copying the logic over from react-redux-firebase. Going to try to get it released some time over the next week.

**Comment by prescottprue** [comment] 2018-11-08 09:29
Included in [v0.6.0-alpha.3 release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.6.0-alpha.3)  🍾

Here are the docs: https://github.com/prescottprue/redux-firestore/tree/next#population. It is basically a direct port over from `react-redux-firebase`, and you actually still pull `populate` (used to construct state with data loaded form populates) from `react-redux-firebase`.

Going to close this for now since it is in pre-release, but I'll still update this thread when releasing it to `latest`. Everyone should feel free to reach out (either here or over gitter) if anything isn't working as expected or just to say "It works!".

**Closed by prescottprue** 2018-11-08 09:29 UTC
Labels: enhancement, help wanted

**Comment by MattJakeman** [comment] 2018-11-09 15:59
Thanks for the update!
I have used it briefly and get the correct data when dumping out to the console. However, when I inspect the redux store it doesn't seem to be storing the populated data. Is this the expected behaviour? EG:

![console](https://user-images.githubusercontent.com/294255/48273236-5e86e380-e438-11e8-91df-cd4aae4424be.png)

![redux](https://user-images.githubusercontent.com/294255/48273057-fd5f1000-e437-11e8-938a-a1702084012b.png)

You can see in the top image that the 'createdBy' field has pulled in the expected user data, but the second image shows the state of the redux store which just has the user ID. I may well be misunderstanding something here but I would have expected redux to have the 'createdBy' user data in as well.

**Comment by prescottprue** [comment] 2018-11-09 22:14
@MattJakeman That is the intention with populate. Many users want to be able to still access the separate un populated data (makes sense since it was queried), so the data is loaded into state just like with normal listeners (dispatch of LISTENER_RESPONSE). Then you use the `populate` utility to build your populated object from the different pieces of state. The settings you pass to it are the same as what you passed to `populates` in the query config.

There is more about why and the examples in [the populate section of the docs](http://react-redux-firebase.com/docs/populate.html) as well as under the [populate part of the recipes section](http://react-redux-firebase.com/docs/recipes/populate.html).

**Comment by MattJakeman** [comment] 2018-11-09 23:29
@prescottprue thanks for the explanation. For some reason I'd got it into my head that redux should be filled with the same data. It's easily workable in that state for me but thought I'd flag it up just in case it was a bug.

Thanks for the speedy response on it and keep up the good work :)
